version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: /back
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: daily
